---
- name: install nginx
  apt: name=nginx update_cache=yes
  sudo: yes
- name: copy nginx config file
  copy: src=roles/nginx/files/nginx.conf dest=/etc/nginx/sites-available/default 
  sudo: yes
  notify: restart nginx
- name: enable configuration
  file: >
    dest=/etc/nginx/sites-enabled/default
    src=/etc/nginx/sites-available/default
    state=link
  sudo: yes
- name: copy index.html
  copy: src=roles/nginx/files/index.html dest=/usr/share/nginx/html/index.html mode=0644
  sudo: yes
  notify: restart nginx
