---
- name: Install MySQL
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  sudo: yes
  with_items:
  - python-mysqldb
  - mysql-server

- name: Start the MySQL service
  sudo: yes
  service: 
    name: mysql 
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create mysql database
  mysql_db: 
    name: "{{ wp_mysql_db }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present

- name: Create mysql user
  mysql_user:
    name: "{{ wp_mysql_user }}" 
    password: "{{ wp_mysql_password }}" 
    login_user: root
    login_password: "{{ mysql_root_password }}"
    priv: "*.*:ALL"
