---
# tasks file for php
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes
- name: Install php
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - php5-mysql
    - php5
    - php5-mcrypt
    - php5-fpm
- name: Install php extensions
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - php5-gd 
    - libssh2-php
